---

- name: Ensure php5 is installed.
  become: yes
  apt: pkg=php5  state=present

- name: Ensure curl is installed.
  become: yes
  apt: pkg=php5-curl state=present

#- name: Ensure mcrypt is installed.
#  become: yes
#  apt: pkg=php5-mcrypt state=present

- name: Ensure gd library is installed.
  become: yes
  apt: pkg=php5-gd state=present

...
